apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-annotations-evsa
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-rlhb-tenant/build-suite-test-application-vnzh/test-annotations-evsa@sha256:34172882917a2e357029ae6303514330b10d4682cbede77cc852c0acd92b27aa
        name: my-nginx
        resources: {}
status: {}
